CREATE TABLE STDKEVI3_Customer(
COSTUMER_ID VARCHAR2(25),
COSTUMER_CATEGORY VARCHAR2(35),
COSTUMER_TYPE VARCHAR2(25),
FIELD_DESCRIPTION VARCHAR2(35),
MANDATORY_VALIDATION VARCHAR2(35),
CONSTRAINT PK_STDKEVI3_Customer PRIMARY KEY (COSTUMER_ID)
);