CREATE TABLE DETAIL_STDKEVI2(
    PRODUCT_ID VARCHAR2(25),
    PRODUCT_CODE VARCHAR2(35),
    PRIMARY KEY (PRODUCT_ID,PRODUCT_CODE),
    CONSTRAINT FK_DETAIL_STDKEVI2 FOREIGN KEY (PRODUCT_ID)
    REFERENCES MASTER_STDKEVI2(PRODUCT_ID)
);


CREATE SYNONYM DETAILS_STDKEVI2 FOR DETAIL_STDKEVI2;