INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY) VALUES ('New');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY) VALUES ('Impulse');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY) VALUES ('Angry');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY) VALUES ('Insistent');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY) VALUES ('Loyal');