INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY,Category_description) VALUES ('New','New Customer');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY,Category_description) VALUES ('Impulse','Impulse Customer');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY,Category_description) VALUES ('Angry','Angry Customer');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY,Category_description) VALUES ('Insistent','Insistent Customer');
INSERT INTO STDKEVI3_C_CATEGORY(COSTUMER_CATEGORY,Category_description) VALUES ('Loyal','Loyal Customer');

commit;