INSERT INTO STDKEVI3_Customer VALUES ('1','New', 'Individual', 'DESCRIPTION 1','Required');
INSERT INTO STDKEVI3_Customer VALUES ('2','New', 'Individual', 'DESCRIPTION 2','Optional');

INSERT INTO STDKEVI3_Customer VALUES ('3','Impulse', 'Individual', 'DESCRIPTION 3','Optional');
INSERT INTO STDKEVI3_Customer VALUES ('4','Impulse', 'Individual', 'DESCRIPTION 4','Required');

INSERT INTO STDKEVI3_Customer VALUES ('5','Loyal', 'Individual', 'DESCRIPTION 5','Required');
INSERT INTO STDKEVI3_Customer VALUES ('6','Loyal', 'Individual', 'DESCRIPTION 6','Required');

INSERT INTO STDKEVI3_Customer VALUES ('7','Angry', 'Individual', 'DESCRIPTION 7','Required');
INSERT INTO STDKEVI3_Customer VALUES ('8','Angry', 'Individual', 'DESCRIPTION 8','Optional');

--

INSERT INTO STDKEVI3_Customer VALUES ('9','New', 'Corporate', 'DESCRIPTION 9','Optional');
INSERT INTO STDKEVI3_Customer VALUES ('10','New', 'Corporate', 'DESCRIPTION 10','Required');

INSERT INTO STDKEVI3_Customer VALUES ('11','Impulse', 'Corporate', 'DESCRIPTION 11','Required');
INSERT INTO STDKEVI3_Customer VALUES ('12','Impulse', 'Corporate', 'DESCRIPTION 12','Required');

INSERT INTO STDKEVI3_Customer VALUES ('13','Loyal', 'Corporate', 'DESCRIPTION 13','Required');
INSERT INTO STDKEVI3_Customer VALUES ('14','Loyal', 'Corporate', 'DESCRIPTION 14','Optional');

INSERT INTO STDKEVI3_Customer VALUES ('15','Angry', 'Corporate', 'DESCRIPTION 15','Optional');
INSERT INTO STDKEVI3_Customer VALUES ('16','Angry', 'Corporate', 'DESCRIPTION 16','Required');
--
INSERT INTO STDKEVI3_Customer VALUES ('17','Insistent', 'Individual', 'DESCRIPTION 17','Required');
INSERT INTO STDKEVI3_Customer VALUES ('18','Insistent', 'Corporate', 'DESCRIPTION 18','Required');

INSERT INTO STDKEVI3_Customer VALUES ('19','New', 'Minor', 'DESCRIPTION 19','Required');
INSERT INTO STDKEVI3_Customer VALUES ('20','New', 'Minor', 'DESCRIPTION 20','Optional');

INSERT INTO STDKEVI3_Customer VALUES ('21','Angry', 'Minor', 'DESCRIPTION 21','Optional');
INSERT INTO STDKEVI3_Customer VALUES ('22','Angry', 'Minor', 'DESCRIPTION 22','Required');

INSERT INTO STDKEVI3_Customer VALUES ('23','Loyal', 'Minor', 'DESCRIPTION 23','Required');
INSERT INTO STDKEVI3_Customer VALUES ('24','Loyal', 'Minor', 'DESCRIPTION 24','Required');


commit;