
INSERT INTO STDKEVI2_CATEGORY(CATEGORY_C,DESCRIPTION_CATEGORY) VALUES ('Commercial','can be further classified into public sector banks, private sector banks, foreign banks and Regional Rural Banks (RRB)');
INSERT INTO STDKEVI2_CATEGORY(CATEGORY_C,DESCRIPTION_CATEGORY) VALUES ('Small Finance','This is a niche banking segment in the country and is aimed to provide financial inclusion to sections of the society that are not served by other banks');
INSERT INTO STDKEVI2_CATEGORY(CATEGORY_C,DESCRIPTION_CATEGORY) VALUES ('Payments','his is a relatively new model of bank in the Indian Banking industry. It was conceptualised by the RBI and is allowed to accept a restricted deposit. The amount is currently limited to Rs.');
INSERT INTO STDKEVI2_CATEGORY(CATEGORY_C,DESCRIPTION_CATEGORY) VALUES ('Co-operative','Co-operative banks are registered under the Cooperative Societies Act, 1912 and they are run by an elected managing committee.');
commit;