INSERT INTO STDKEVI2_CODE(PRODUCT_CODE) VALUES ('AACO');
INSERT INTO STDKEVI2_CODE(PRODUCT_CODE) VALUES ('AECO');
INSERT INTO STDKEVI2_CODE(PRODUCT_CODE) VALUES ('CCAO');
INSERT INTO STDKEVI2_CODE(PRODUCT_CODE) VALUES ('AMEX');
INSERT INTO STDKEVI2_CODE(PRODUCT_CODE) VALUES ('AMEK');
