
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY) VALUES ('MARA');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY) VALUES ('VBAK');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY) VALUES ('VBAP');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY) VALUES ('EKPO');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY) VALUES ('BSEG');