  Insert into ertb_msgs values('stdkevi1','ENG','Priority in High so the amount should be greater than 1000','E','N','','','','','','','','','','' );
  Insert into ertb_msgs values('stdkevi2','ENG','Priority in Mid so the amount should be greater than 500','E','N','','','','','','','','','','' );
  Insert into ertb_msgs values('stdkevi3','ENG','The date can`t be in the future','E','N','','','','','','','','','','' );
COMMIT;