  Insert into ertb_msgs values('stdkevi1','ENG','PRIORITY IS HIGH SO THE AMOUNT SHOULD BE GREATER THAN 1000','E','N','','','','','','','','','','' );
  Insert into ertb_msgs values('stdkevi2','ENG','PRIORITY IS MID SO THE AMOUNT SHOULD BE GREATER THAN 500','E','N','','','','','','','','','','' );
  Insert into ertb_msgs values('stdkevi3','ENG','THE DATE CANT BE IN THE FUTURE','E','N','','','','','','','','','','' );
COMMIT;