INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY,DESCRIPTION_CATEGORY) VALUES ('Occupational','working in a hospital, uranium mine, or nuclear power plant');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY, DESCRIPTION_CATEGORY) VALUES ('Public','aircrew and astronauts exposed to cosmic radiation');
INSERT INTO STDKEVI1_CATEGORY(EXPOSURE_CATEGORY, DESCRIPTION_CATEGORY) VALUES ('Medical','in the immediate response to an accident');
commit;